name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: 22
        cache: 'yarn'

    - name: Install dependencies
      run: yarn

    - name: Build Package
      run: yarn build

    - name: Run tests with coverage
      run: yarn coverage

    - uses: codecov/codecov-action@v4
      with:
        use_oidc: true
        files: ./coverage/lcov.info
